Use the classloader from the object we got to avoid NoClassDefFoundErrors
When trying to register a event method from a class with a classloader different
from Sponge's, when we try to define the class, it throws a NoClassDefFoundError
due to the class being unaccessable from the current classloader.