Use throwable when catching phase errors. Fixes #1273
Some mods may cause a NoClassDefFoundError due to using a client class on
server side. Due to this, we must use a Throwable instead of an Exception
to guarantee we catch all phase errors.